#!/usr/bin/env node
// console.log('hello', process.argv[2]);
require('shelljs/global');
if (!which('git')) {
    echo('Sorry, this script requires git');
    exit(1);
}

const testFtl = '/Users/hc/workspace/store-app/store-app/src/main/resources/templates/mobile/appStore.ftl';
// const testFtl = 'D:\\test\\test.ftl'; //windows 路径为两个反斜线

const distDir = '/Users/hc/workspace/mobile_store/dist';
const distJs = `${distDir}/js/**.*`;
const distCss = `${distDir}/css/**.*`;

const targetDir = '/Users/hc/workspace/store-app/store-app/src/main/resources/static';
const targetCssDir = `${targetDir}/css/mobile`;
const targetJsDir = `${targetDir}/js/mobile`;

const jsPrefix = ['vendor', 'main', 'manifest'];
const cssPrefix = ['vendor', 'main'];

// 删除.gz
rm(`${distDir}/js/*.gz`);

jsPrefix.forEach((file) => {
    rm(`${targetJsDir}/${file}.*`);
}); 

cssPrefix.forEach((file) => {
    rm(`${targetCssDir}/${file}.*`);
});

cp('-R', distJs, targetJsDir);
cp('-R', distCss, targetCssDir);

console.log('\njs==============================\n');
ls(distJs).forEach((file) => {
    console.log(file);
});

console.log('\ncss============================\n');
ls(distCss).forEach((file) => {
    console.log(file);
});

const cssMainRx = /css\/mobile\/main.[a-z0-9]{6}.css/g;
const cssVendorRx = /css\/mobile\/vendor.[a-z0-9]{6}.css/g;

ls(`${targetCssDir}/*.css`).forEach((css) => {
    const mainCssPath = css.match(cssMainRx);
    const vendorCssPath = css.match(cssVendorRx);

    if (mainCssPath) {
        sed('-i', cssMainRx, mainCssPath[0], testFtl);
    }
    if (vendorCssPath) {
        sed('-i', cssVendorRx, vendorCssPath[0], testFtl);
    }

});

const jsMainRx = /js\/mobile\/main.[a-z0-9]{6}.js/g;
const jsVendorRx = /js\/mobile\/vendor.[a-z0-9]{6}.js/g;
const jsManifestRx = /js\/mobile\/manifest.[a-z0-9]{6}.js/g;

ls(`${targetJsDir}/*.js`).forEach((js) => {
    const mainJsPath = js.match(jsMainRx);
    const vendorJsPath = js.match(jsVendorRx);
    const manifestJsPath = js.match(jsManifestRx);

    if (mainJsPath) {
        sed('-i', jsMainRx, mainJsPath[0], testFtl);
    }
    if (vendorJsPath) {
        sed('-i', jsVendorRx, vendorJsPath[0], testFtl);
    }
    if (manifestJsPath) {
        sed('-i', jsManifestRx, manifestJsPath[0], testFtl);
    }

});

console.log('\ntemplate==============================\n')
exec(`cat ${testFtl}`);
